### ISSUE TITLE
URL wrong in readme

### ISSUE THREAD

**Issue by CasparWaara** [HartsyAI/SwarmUI-MagicPromptExtension#19]
Openrouter URL is wrong in readme. It's pointing to .io but it is .ai 

https://github.com/HartsyAI/SwarmUI-MagicPromptExtension/pull/20

**Comment by rustyorb** [comment]
I changed the line in the config file, in the extensions directory to the following to resolve this issue:

 "BaseUrl": "https://openrouter.ai"
 
 I think prior to changing it was "https://openrouter.ai/api/va", which is correct but then it looks to me like the /api/v1 is getting added again.

**Comment by southbayjay** [comment]
> I changed the line in the config file, in the extensions directory to the following to resolve this issue:
> 
> "BaseUrl": "https://openrouter.ai"
> 
> I think prior to changing it was "https://openrouter.ai/api/v1", which is correct but then it looks to me like the /api/v1 is getting added again.

Are you having issues with the default configuration? It's working fine on my end.

**Comment by kalebbroo** [comment]
This has been resolved I just need to finish the update.

**Comment by Agiltech-com-au** [comment]
I still get invalid URI with open ai as well. If you just enter the api key it shows the models list so api key working. But invalid link error
